org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.isolated-projects=true
org.gradle.vfs.watch=true
org.gradle.java.installations.auto-detect=true
org.gradle.configuration-cache.problems=warn
org.gradle.tooling.parallel=true
org.gradle.workers.max=4
kotlin.code.style=official
android.nonTransitiveRClass=true
android.useAndroidX=true
android.enableJetifier=false
googleServices.missing.passthrough=true
ksp.incremental=true
ksp.incremental.intermodule=true